### ISSUE TITLE
Error parsing message in TikTokLive's deserialize_message function in utilities.py

### ISSUE THREAD

**Issue by ahaydarli** [isaackogan/TikTokLive#109]
`Traceback (most recent call last):
  File "/home/ubuntu/tok-server/main.py", line 61, in <module>
    client.run()
  File "/home/ubuntu/tok-server/.venv/lib/python3.10/site-packages/TikTokLive/client/base.py", line 371, in run
    self.loop.run_until_complete(self._start())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/ubuntu/tok-server/.venv/lib/python3.10/site-packages/TikTokLive/client/base.py", line 347, in _start
    await self.start()
  File "/home/ubuntu/tok-server/.venv/lib/python3.10/site-packages/TikTokLive/client/base.py", line 338, in start
    await self._connect()
  File "/home/ubuntu/tok-server/.venv/lib/python3.10/site-packages/TikTokLive/client/base.py", line 293, in _connect
    webcast_response: Dict[str, Union[dict, str]] = await self.__fetch_room_data()
  File "/home/ubuntu/tok-server/.venv/lib/python3.10/site-packages/TikTokLive/client/base.py", line 162, in __fetch_room_data
    webcast_response = await self.http.get_deserialized_object_from_signing_api("webcast/fetch/", self.http.params, "WebcastResponse")
  File "/home/ubuntu/tok-server/.venv/lib/python3.10/site-packages/TikTokLive/client/httpx.py", line 194, in get_deserialized_object_from_signing_api
    return deserialize_message(schema, response)
  File "/home/ubuntu/tok-server/.venv/lib/python3.10/site-packages/TikTokLive/proto/utilities.py", line 21, in deserialize_message
    webcast_data.ParseFromString(obj)
google.protobuf.message.DecodeError: Error parsing message`

**Comment by 8qBITs** [comment]
Same issue, at accurs on all libraries NodeJS, C#, Golang and this Python library. Tiktok has made a major change to something.

**Comment by Matthew54e** [comment]
Same here as well. Looks like TikTok likely changed the format of this message type?

**Comment by ahaydarli** [comment]
I think that my IP was blocked

**Comment by richiec77** [comment]
Any idea when this will get looked at?

**Comment by 8qBITs** [comment]
> 

It was fixed hours after this was opened, someone should close this issue.

**Comment by isaackogan** [comment]
Fixed
