### ISSUE TITLE
Error when download livestream

### ISSUE THREAD

**Issue by hechay** [isaackogan/TikTokLive#115]
**Describe the bug**
I tried to run code demo and got this error

**ERROR:asyncio:Exception in callback AsyncIOEventEmitter._emit_run.<locals>.callback(<Task finishe...REAK_EVENT'")>) at /usr/local/lib/python3.7/dist-packages/pyee/asyncio.py:65
handle: <Handle AsyncIOEventEmitter._emit_run.<locals>.callback(<Task finishe...REAK_EVENT'")>) at /usr/local/lib/python3.7/dist-packages/pyee/asyncio.py:65>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.7/dist-packages/pyee/asyncio.py", line 71, in callback
    self.emit("error", exc)
  File "/usr/local/lib/python3.7/dist-packages/pyee/base.py", line 179, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "/usr/local/lib/python3.7/dist-packages/pyee/base.py", line 139, in _emit_handle_potential_error
    raise error
  File "demo.py", line 21, in on_connect
    client.stop_download()
  File "/usr/local/lib/python3.7/dist-packages/TikTokLive/client/base.py", line 509, in stop_download
    os.kill(self.ffmpeg.ffmpeg.process.pid, signal.CTRL_BREAK_EVENT)
AttributeError: module 'signal' has no attribute 'CTRL_BREAK_EVENT'**

Not sure it is a bug or not, because the stream still download OK. 

**Desktop (please complete the following information):**
 - OS: Ubuntu 18

**Comment by isaackogan** [comment]
Very very interesting. Not sure lol
