### ISSUE TITLE
google.protobuf.message.DecodeError: Error parsing message

### ISSUE THREAD

**Issue by shiwentang** [isaackogan/TikTokLive#117]
Hello, 

When I run the example, it reports the error below. 

Traceback (most recent call last):
  File "/Users/shiwen/Desktop/tiktoklive/test.py", line 123, in <module>
    client.run()
  File "/Users/shiwen/Desktop/tiktoklive/TikTokLive/client/base.py", line 376, in run
    self.loop.run_until_complete(self._start())  # TODO this is the reason the event loop stops. run until complete runs until the future ends, see docs
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/shiwen/Desktop/tiktoklive/TikTokLive/client/base.py", line 352, in _start
    await self.start()
  File "/Users/shiwen/Desktop/tiktoklive/TikTokLive/client/base.py", line 343, in start
    await self._connect()
  File "/Users/shiwen/Desktop/tiktoklive/TikTokLive/client/base.py", line 298, in _connect
    webcast_response: Dict[str, Union[dict, str]] = await self._fetch_room_data()
  File "/Users/shiwen/Desktop/tiktoklive/TikTokLive/client/base.py", line 167, in _fetch_room_data
    webcast_response = await self.http.get_deserialized_object_from_signing_api("webcast/fetch/", self.http.params, "WebcastResponse")
  File "/Users/shiwen/Desktop/tiktoklive/TikTokLive/client/httpx.py", line 200, in get_deserialized_object_from_signing_api
    return deserialize_message(schema, response)
  File "/Users/shiwen/Desktop/tiktoklive/TikTokLive/proto/utilities.py", line 21, in deserialize_message
    webcast_data.ParseFromString(obj)
google.protobuf.message.DecodeError: Error parsing message

**Comment by Hypnotistchris** [comment]
I am seeing the same issue

**Comment by 128px** [comment]
Same here, glad it's not just me.

**Comment by guilhermedevvv** [comment]
nodejs' lib is also not working

**Comment by isaackogan** [comment]
Issue fixed, internal microservice restarted
