### ISSUE TITLE
google.protobuf.message.DecodeError: Error parsing message Error

### ISSUE THREAD

**Issue by Hypnotistchris** [isaackogan/TikTokLive#118]
Started this morning on my existing working code.

**Comment by isaackogan** [comment]
Issue fixed, internal microservice restarted

**Comment by Reystud** [comment]
Hello !
It seems the microservice as failed again ?

`Traceback (most recent call last):
  File "/home/minecraft/tiktok-live-battle/reystud.py", line 43, in <module>
    client.run()
  File "/home/minecraft/.local/lib/python3.9/site-packages/TikTokLive/client/base.py", line 376, in run
    self.loop.run_until_complete(self._start())  # TODO this is the reason the event loop stops. run until complete runs until the future ends, see docs
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/minecraft/.local/lib/python3.9/site-packages/TikTokLive/client/base.py", line 352, in _start
    await self.start()
  File "/home/minecraft/.local/lib/python3.9/site-packages/TikTokLive/client/base.py", line 343, in start
    await self._connect()
  File "/home/minecraft/.local/lib/python3.9/site-packages/TikTokLive/client/base.py", line 298, in _connect
    webcast_response: Dict[str, Union[dict, str]] = await self._fetch_room_data()
  File "/home/minecraft/.local/lib/python3.9/site-packages/TikTokLive/client/base.py", line 167, in _fetch_room_data
    webcast_response = await self.http.get_deserialized_object_from_signing_api("webcast/fetch/", self.http.params, "WebcastResponse")
  File "/home/minecraft/.local/lib/python3.9/site-packages/TikTokLive/client/httpx.py", line 200, in get_deserialized_object_from_signing_api
    return deserialize_message(schema, response)
  File "/home/minecraft/.local/lib/python3.9/site-packages/TikTokLive/proto/utilities.py", line 21, in deserialize_message
    webcast_data.ParseFromString(obj)
google.protobuf.message.DecodeError: Error parsing message`
