### ISSUE TITLE
Issues with using proxies

### ISSUE THREAD

**Issue by fantasmic** [isaackogan/TikTokLive#122]
Due to work reasons, it is necessary to use a proxy to access TikTok,After executing the introductory example, the following error will be reported

C:\Users\EDZ\.virtualenvs\tklive-PAoHKgaW\Scripts\python.exe E:\python\tklive\main.py 
Traceback (most recent call last):
  File "C:\Users\EDZ\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 480, in finish_recv
    return ov.getresult()
OSError: [WinError 64] The specified network name is no longer available。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\EDZ\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 282, in _loop_reading
    length = fut.result()
  File "C:\Users\EDZ\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 812, in _poll
    value = callback(transferred, key, ov)
  File "C:\Users\EDZ\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 484, in finish_recv
    raise ConnectionResetError(*exc.args)
ConnectionResetError: [WinError 64] The specified network name is no longer available。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\EDZ\.virtualenvs\tklive-PAoHKgaW\lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "C:\Users\EDZ\.virtualenvs\tklive-PAoHKgaW\lib\site-packages\httpcore\backends\asyncio.py", line 78, in start_tls
    raise exc
  File "C:\Users\EDZ\.virtualenvs\tklive-PAoHKgaW\lib\site-packages\httpcore\backends\asyncio.py", line 69, in start_tls
    ssl_stream = await anyio.streams.tls.TLSStream.wrap(
  File "C:\Users\EDZ\.virtualenvs\tklive-PAoHKgaW\lib\site-packages\anyio\streams\tls.py", line 122, in wrap
    await wrapper._call_sslobject_method(ssl_object.do_handshake)
  File "C:\Users\EDZ\.virtualenvs\tklive-PAoHKgaW\lib\site-packages\anyio\streams\tls.py", line 137, in _call_sslobject_method
    data = await self.transport_stream.receive()
  File "C:\Users\EDZ\.virtualenvs\tklive-PAoHKgaW\lib\site-packages\anyio\_backends\_asyncio.py", line 1274, in receive
    raise self._protocol.exception
anyio.BrokenResourceError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\EDZ\.virtualenvs\tklive-PAoHKgaW\lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "C:\Users\EDZ\.virtualenvs\tklive-PAoHKgaW\lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "C:\Users\EDZ\.virtualenvs\tklive-PAoHKgaW\lib\site-packages\httpcore\_async\connection_pool.py", line 253, in handle_async_request
    raise exc
  File "C:\Users\EDZ\.virtualenvs\tklive-PAoHKgaW\lib\site-packages\httpcore\_async\connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "C:\Users\EDZ\.virtualenvs\tklive-PAoHKgaW\lib\site-packages\httpcore\_async\connection.py", line 86, in handle_async_request
    raise exc
  File "C:\Users\EDZ\.virtualenvs\tklive-PAoHKgaW\lib\site-packages\httpcore\_async\connection.py", line 63, in handle_async_request
    stream = await self._connect(request)
  File "C:\Users\EDZ\.virtualenvs\tklive-PAoHKgaW\lib\site-packages\httpcore\_async\connection.py", line 150, in _connect
    stream = await stream.start_tls(**kwargs)
  File "C:\Users\EDZ\.virtualenvs\tklive-PAoHKgaW\lib\site-packages\httpcore\backends\asyncio.py", line 66, in start_tls
    with map_exceptions(exc_map):
  File "C:\Users\EDZ\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\EDZ\.virtualenvs\tklive-PAoHKgaW\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\EDZ\.virtualenvs\tklive-PAoHKgaW\lib\site-packages\TikTokLive\client\base.py", line 150, in _fetch_room_id
    html: str = await self.http.get_livestream_page_html(self.__unique_id)
  File "C:\Users\EDZ\.virtualenvs\tklive-PAoHKgaW\lib\site-packages\TikTokLive\client\httpx.py", line 183, in get_livestream_page_html
    response: bytes = await self.__httpx_get_bytes(f"{config.TIKTOK_URL_WEB}@{unique_id}/live")
  File "C:\Users\EDZ\.virtualenvs\tklive-PAoHKgaW\lib\site-packages\TikTokLive\client\httpx.py", line 98, in __httpx_get_bytes
    response: httpx.Response = await client.get(url, headers=self.headers, timeout=self.timeout)
  File "C:\Users\EDZ\.virtualenvs\tklive-PAoHKgaW\lib\site-packages\httpx\_client.py", line 1754, in get
    return await self.request(
  File "C:\Users\EDZ\.virtualenvs\tklive-PAoHKgaW\lib\site-packages\httpx\_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "C:\Users\EDZ\.virtualenvs\tklive-PAoHKgaW\lib\site-packages\httpx\_client.py", line 1617, in send
    response = await self._send_handling_auth(
  File "C:\Users\EDZ\.virtualenvs\tklive-PAoHKgaW\lib\site-packages\httpx\_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "C:\Users\EDZ\.virtualenvs\tklive-PAoHKgaW\lib\site-packages\httpx\_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "C:\Users\EDZ\.virtualenvs\tklive-PAoHKgaW\lib\site-packages\httpx\_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
  File "C:\Users\EDZ\.virtualenvs\tklive-PAoHKgaW\lib\site-packages\httpx\_transports\default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
  File "C:\Users\EDZ\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\EDZ\.virtualenvs\tklive-PAoHKgaW\lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\python\tklive\main.py", line 25, in <module>
    client.run()
  File "C:\Users\EDZ\.virtualenvs\tklive-PAoHKgaW\lib\site-packages\TikTokLive\client\base.py", line 376, in run
    self.loop.run_until_complete(self._start())  # TODO this is the reason the event loop stops. run until complete runs until the future ends, see docs
  File "C:\Users\EDZ\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\EDZ\.virtualenvs\tklive-PAoHKgaW\lib\site-packages\TikTokLive\client\base.py", line 352, in _start
    await self.start()
  File "C:\Users\EDZ\.virtualenvs\tklive-PAoHKgaW\lib\site-packages\TikTokLive\client\base.py", line 343, in start
    await self._connect()
  File "C:\Users\EDZ\.virtualenvs\tklive-PAoHKgaW\lib\site-packages\TikTokLive\client\base.py", line 283, in _connect
    await self._fetch_room_id()
  File "C:\Users\EDZ\.virtualenvs\tklive-PAoHKgaW\lib\site-packages\TikTokLive\client\base.py", line 155, in _fetch_room_id
    await self._on_error(ex, FailedFetchRoomInfo("Failed to fetch room id from Webcast, see stacktrace for more info."))
  File "C:\Users\EDZ\.virtualenvs\tklive-PAoHKgaW\lib\site-packages\TikTokLive\client\client.py", line 68, in _on_error
    raise _exc
  File "C:\Users\EDZ\.virtualenvs\tklive-PAoHKgaW\lib\site-packages\TikTokLive\client\client.py", line 62, in _on_error
    raise append from original
TikTokLive.types.errors.FailedFetchRoomInfo: Failed to fetch room id from Webcast, see stacktrace for more info.

Process finished with exit code 1

system
os : windows10
python : 3.10

**Comment by qraccess** [comment]
I have set http proxy, but how to set websocket proxy

**Comment by isaackogan** [comment]
You cannot set the websocket proxy.
