### ISSUE TITLE
ssl.SSLWantReadError: The operation did not complete (read). 

### ISSUE THREAD

**Issue by aviongeno** [isaackogan/TikTokLive#132]
**Describe the bug**

The error seems to happen when attempting to connect to a tiktok stream. It was working this morning and then all of a sudden it is no longer working. This could be because of an update on my PC I guess as my computer updated. 

Exception in thread Thread-1 (start_client):
Traceback (most recent call last):
  File "C:\Users\{user}\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\streams\tls.py", line 130, in _call_sslobject_method
    result = func(*args)
  File "C:\Users\{user}\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 917, in read
    v = self._sslobj.read(len)
ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:2548)

** Steps to Reprocess **

client: TikTokLiveClient = TikTokLiveClient(unique_id="@ahtaaa_") 
async def main(client: TikTokLiveClient):
        while not client.connected:
            try:
                await client.start()
            except:
                print(f"User `@{client.unique_id}` seems to be offline, retrying after 1 minute...")
                await asyncio.sleep(60)

**Comment by jnativel** [comment]
I have the same problem !

ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:2578)

**Comment by GabrielMendesdc** [comment]
Same here. Code was working yesterday.
latest tiktoklive version,  win10 with no changes, python 3.10.0

```
Traceback (most recent call last):
  File "C:\Users\gabriel\att\lib\site-packages\anyio\streams\tls.py", line 130, in _call_sslobject_method
    result = func(*args)
  File "C:\Users\gabriel\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 916, in read
    v = self._sslobj.read(len)
ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:2536)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gabriel\att\lib\site-packages\httpcore\backends\asyncio.py", line 34, in read
    return await self._stream.receive(max_bytes=max_bytes)
  File "C:\Users\gabriel\att\lib\site-packages\anyio\streams\tls.py", line 195, in receive
    data = await self._call_sslobject_method(self._ssl_object.read, max_bytes)
  File "C:\Users\gabriel\att\lib\site-packages\anyio\streams\tls.py", line 137, in _call_sslobject_method
    data = await self.transport_stream.receive()
  File "C:\Users\gabriel\att\lib\site-packages\anyio\_backends\_asyncio.py", line 1265, in receive       
    await self._protocol.read_event.wait()
  File "C:\Users\gabriel\AppData\Local\Programs\Python\Python310\lib\asyncio\locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gabriel\att\lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "C:\Users\gabriel\att\lib\site-packages\httpcore\backends\asyncio.py", line 32, in read
    with anyio.fail_after(timeout):
  File "C:\Users\gabriel\att\lib\site-packages\anyio\_core\_tasks.py", line 118, in __exit__
    raise TimeoutError
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gabriel\att\lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "C:\Users\gabriel\att\lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "C:\Users\gabriel\att\lib\site-packages\httpcore\_async\connection_pool.py", line 253, in handle_async_request
    raise exc
  File "C:\Users\gabriel\att\lib\site-packages\httpcore\_async\connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "C:\Users\gabriel\att\lib\site-packages\httpcore\_async\connection.py", line 90, in handle_async_request
    return await self._connection.handle_async_request(request)
  File "C:\Users\gabriel\att\lib\site-packages\httpcore\_async\http11.py", line 112, in handle_async_request
    raise exc
  File "C:\Users\gabriel\att\lib\site-packages\httpcore\_async\http11.py", line 91, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
  File "C:\Users\gabriel\att\lib\site-packages\httpcore\_async\http11.py", line 155, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
  File "C:\Users\gabriel\att\lib\site-packages\httpcore\_async\http11.py", line 191, in _receive_event
    data = await self._network_stream.read(
  File "C:\Users\gabriel\att\lib\site-packages\httpcore\backends\asyncio.py", line 31, in read
    with map_exceptions(exc_map):
  File "C:\Users\gabriel\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\gabriel\att\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.ReadTimeout
```

**Comment by thearthouse** [comment]
same

**Comment by TrevinFluker** [comment]
Same!

**Comment by PWSMarcello** [comment]
yes doesnt work anymore :(

**Comment by isaackogan** [comment]
Is this still ocurring?

**Comment by PWSMarcello** [comment]
Hi, Nope!

Isaac Kogan ***@***.***> schrieb am Sa., 26. Aug. 2023, 04:12:
