### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by senluowanxiang1** [isaackogan/TikTokLive#147]
Traceback (most recent call last):
  File "D:\WorkTool\Python\Lib\site-packages\anyio\_core\_tasks.py", line 115, in fail_after
    yield cancel_scope
  File "D:\WorkTool\Python\Lib\site-packages\httpcore\_backends\anyio.py", line 114, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\WorkTool\Python\Lib\site-packages\anyio\_core\_sockets.py", line 217, in connect_tcp
    async with create_task_group() as tg:
  File "D:\WorkTool\Python\Lib\site-packages\anyio\_backends\_asyncio.py", line 674, in __aexit__
    raise cancelled_exc_while_waiting_tasks
  File "D:\WorkTool\Python\Lib\site-packages\anyio\_backends\_asyncio.py", line 654, in __aexit__
    await asyncio.wait(self.cancel_scope._tasks)
  File "D:\WorkTool\Python\Lib\asyncio\tasks.py", line 418, in wait
    return await _wait(fs, timeout, return_when, loop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\WorkTool\Python\Lib\asyncio\tasks.py", line 525, in _wait
    await waiter
asyncio.exceptions.CancelledError: Cancelled by cancel scope 263800e6690

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WorkTool\Python\Lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "D:\WorkTool\Python\Lib\site-packages\httpcore\_backends\anyio.py", line 113, in connect_tcp
    with anyio.fail_after(timeout):
  File "D:\WorkTool\Python\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\WorkTool\Python\Lib\site-packages\anyio\_core\_tasks.py", line 118, in fail_after
    raise TimeoutError
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\WorkTool\Python\Lib\site-packages\httpx\_transports\default.py", line 66, in map_httpcore_exceptions
    yield
  File "D:\WorkTool\Python\Lib\site-packages\httpx\_transports\default.py", line 366, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\WorkTool\Python\Lib\site-packages\httpcore\_async\connection_pool.py", line 262, in handle_async_request
    raise exc
  File "D:\WorkTool\Python\Lib\site-packages\httpcore\_async\connection_pool.py", line 245, in handle_async_request
    response = await connection.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\WorkTool\Python\Lib\site-packages\httpcore\_async\connection.py", line 99, in handle_async_request
    raise exc
  File "D:\WorkTool\Python\Lib\site-packages\httpcore\_async\connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\WorkTool\Python\Lib\site-packages\httpcore\_async\connection.py", line 124, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\WorkTool\Python\Lib\site-packages\httpcore\_backends\auto.py", line 31, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\WorkTool\Python\Lib\site-packages\httpcore\_backends\anyio.py", line 112, in connect_tcp
    with map_exceptions(exc_map):
  File "D:\WorkTool\Python\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\WorkTool\Python\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\WorkTool\Python\Lib\site-packages\TikTokLive\client\base.py", line 150, in _fetch_room_id
    html: str = await self.http.get_livestream_page_html(self.__unique_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\WorkTool\Python\Lib\site-packages\TikTokLive\client\httpx.py", line 183, in get_livestream_page_html
    response: bytes = await self.__httpx_get_bytes(f"{config.TIKTOK_URL_WEB}@{unique_id}/live")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\WorkTool\Python\Lib\site-packages\TikTokLive\client\httpx.py", line 98, in __httpx_get_bytes
    response: httpx.Response = await client.get(url, headers=self.headers, timeout=self.timeout)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\WorkTool\Python\Lib\site-packages\httpx\_client.py", line 1757, in get
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "D:\WorkTool\Python\Lib\site-packages\httpx\_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\WorkTool\Python\Lib\site-packages\httpx\_client.py", line 1617, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\WorkTool\Python\Lib\site-packages\httpx\_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\WorkTool\Python\Lib\site-packages\httpx\_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\WorkTool\Python\Lib\site-packages\httpx\_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\WorkTool\Python\Lib\site-packages\httpx\_transports\default.py", line 365, in handle_async_request
    with map_httpcore_exceptions():
  File "D:\WorkTool\Python\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\WorkTool\Python\Lib\site-packages\httpx\_transports\default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Git_Project\TikTokPython\toktik_P.py", line 25, in <module>
    client.run()
  File "D:\WorkTool\Python\Lib\site-packages\TikTokLive\client\base.py", line 376, in run
    self.loop.run_until_complete(self._start())  # TODO this is the reason the event loop stops. run until complete runs until the future ends, see docs
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\WorkTool\Python\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\WorkTool\Python\Lib\site-packages\TikTokLive\client\base.py", line 352, in _start
    await self.start()
  File "D:\WorkTool\Python\Lib\site-packages\TikTokLive\client\base.py", line 343, in start
    await self._connect()
  File "D:\WorkTool\Python\Lib\site-packages\TikTokLive\client\base.py", line 283, in _connect
    await self._fetch_room_id()
  File "D:\WorkTool\Python\Lib\site-packages\TikTokLive\client\base.py", line 155, in _fetch_room_id
    await self._on_error(ex, FailedFetchRoomInfo("Failed to fetch room id from Webcast, see stacktrace for more info."))
  File "D:\WorkTool\Python\Lib\site-packages\TikTokLive\client\client.py", line 68, in _on_error
    raise _exc
  File "D:\WorkTool\Python\Lib\site-packages\TikTokLive\client\client.py", line 62, in _on_error
    raise append from original
TikTokLive.types.errors.FailedFetchRoomInfo: Failed to fetch room id from Webcast, see stacktrace for more info.

Please help me solve this problem, thank you. I am a Python novice.

**Comment by isaackogan** [comment]
ni
