### ISSUE TITLE
client init error with "__init__() got multiple values for argument 'reason'"

### ISSUE THREAD

**Issue by juzhesys** [isaackogan/TikTokLive#181]
v6.0.1
MacOS intel
py 3.8.13

error msg as follow:
[WARNING] client reconnecting https://www.tiktok.com/@anwarsizent/live
Task exception was never retrieved
future: <Task finished name='Task-9' coro=<TikTokLiveMonitor.detect_monitoring() done, defined at /Users/User/PycharmProjects/tiktok_live/maingui.py:238> exception=TypeError("__init__() got multiple values for argument 'reason'")>
Traceback (most recent call last):
  File "/Users/User/PycharmProjects/tiktok_live/maingui.py", line 247, in detect_monitoring
    await client.connect()
  File "/Users/User/.pyenv/versions/3.8.13/lib/python3.8/site-packages/TikTokLive/client/client.py", line 152, in connect
    task: Task = await self.start(**kwargs)
  File "/Users/User/.pyenv/versions/3.8.13/lib/python3.8/site-packages/TikTokLive/client/client.py", line 126, in start
    webcast_response: WebcastResponse = await self._web.fetch_sign_fetch()
  File "/Users/User/.pyenv/versions/3.8.13/lib/python3.8/site-packages/TikTokLive/client/web/routes/fetch_sign.py", line 127, in __call__
    raise SignatureRateLimitError(
  File "/Users/User/.pyenv/versions/3.8.13/lib/python3.8/site-packages/TikTokLive/client/web/routes/fetch_sign.py", line 73, in __init__
    super().__init__(reason=SignAPIError.ErrorReason.RATE_LIMIT, *args)
TypeError: __init__() got multiple values for argument 'reason'

**Comment by juzhesys** [comment]
async def detect_monitoring(self, url):
        client = self.clients.get(url)
        if client:
            if client.connected:
                print(f'[INFO] client {url} is live')
            else:
                print(f'[WARNING] client reconnecting {url}')
                await client.connect()

**Comment by TanMink** [comment]
tôi cũng bị lỗi tương tự

**Comment by isaackogan** [comment]
This is a rate limit error. Seems that the message handling was improper causing an exception to be raised when raising the exception (meta, I know).

See fixed release https://github.com/isaackogan/TikTokLive/releases/tag/v6.0.1-post1
