### ISSUE TITLE
Some sort of error popping up all the time

### ISSUE THREAD

**Issue by Zibux** [isaackogan/TikTokLive#20]
Hello I am getting this type of error sometimes.

`Error while fetching room data
ERROR:root:Traceback (most recent call last):
  File "C:\Users\Gatis_2\AppData\Local\Programs\Python\Python310\lib\site-packages\TikTokLive\client\base.py", line 152, in __fetch_room_polling
    await self.__fetch_room_data()
  File "C:\Users\Gatis_2\AppData\Local\Programs\Python\Python310\lib\site-packages\TikTokLive\client\base.py", line 174, in __fetch_room_data
    await self._handle_webcast_messages(webcast_response)
  File "C:\Users\Gatis_2\AppData\Local\Programs\Python\Python310\lib\site-packages\TikTokLive\client\client.py", line 67, in _handle_webcast_messages
    response: Optional[AbstractEvent] = self.__parse_message(webcast_message=message)
  File "C:\Users\Gatis_2\AppData\Local\Programs\Python\Python310\lib\site-packages\TikTokLive\client\client.py", line 117, in __parse_message
    webcast_message["gift"] = json.loads(gift)
  File "C:\Users\Gatis_2\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

Error while fetching room data`

I am also getting this at start
`PS C:\Users\Gatis_2\Desktop\Tiktoklive> & C:/Users/Gatis_2/AppData/Local/Programs/Python/Python310/python.exe c:/Users/Gatis_2/Desktop/Tiktoklive/AccTiktok.py
c:\Users\Gatis_2\Desktop\Tiktoklive\AccTiktok.py:36: RuntimeWarning: coroutine 'BaseClient.retrieve_available_gifts' was never awaited
  client.retrieve_available_gifts()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback`

I am using Stable version of python Python 3.10.4

I think sometimes it makes some gifts skip.

webcast_message.get("giftJson") sends beck None

**Comment by isaackogan** [comment]
Known issue: https://github.com/zerodytrash/TikTok-Live-Connector/issues/23#issuecomment-1097087186

**Comment by isaackogan** [comment]
Fixed in https://github.com/isaackogan/TikTokLive/issues/15

**Comment by isaackogan** [comment]
Fixed in Release https://github.com/isaackogan/TikTokLive/releases/tag/v0.8.2
