### ISSUE TITLE
TikTokLive.client.errors.UserOfflineError

### ISSUE THREAD

**Issue by Ikaros-521** [isaackogan/TikTokLive#203]
### Describe the bug

The demo connection program I ran reported the following error

```
[TikTokLive] INFO from tests\test_tiktok\v6.py:36 — Requested client is live!
Traceback (most recent call last):
  File "E:\GitHub_pro\AI-Vtuber\tests\test_tiktok\v6.py", line 43, in <module>
    asyncio.run(check_loop())
  File "e:\GitHub_pro\AI-Vtuber\Miniconda3\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "e:\GitHub_pro\AI-Vtuber\Miniconda3\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "E:\GitHub_pro\AI-Vtuber\tests\test_tiktok\v6.py", line 37, in check_loop
    await client.connect()
  File "e:\GitHub_pro\AI-Vtuber\Miniconda3\lib\site-packages\TikTokLive\client\client.py", line 153, in connect
    task: Task = await self.start(**kwargs)
  File "e:\GitHub_pro\AI-Vtuber\Miniconda3\lib\site-packages\TikTokLive\client\client.py", line 120, in start
    raise UserOfflineError()
TikTokLive.client.errors.UserOfflineError
```

### Expected Behaviour

normal listen

### Actual Behaviour
*If applicable, include screenshots!*

![image](https://github.com/isaackogan/TikTokLive/assets/40910637/94682fb3-9412-45b0-85b6-370afbfe06bf)

### Package Version

My version of TikTokLive is `6.0.3`.

### Operating System

- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Other (Specifically, `...`)

### Anything Else

If there's anything else, add it here.

Network is normal，use proxy also error

**Comment by isaackogan** [comment]
This happens when the stream is rated 18+. Provide a sessionid.

**Comment by isaackogan** [comment]
A new version will come out with a better error message. You can also disable fetch_room_info.
