### ISSUE TITLE
httpx.Timeout Error

### ISSUE THREAD

**Issue by RyanArmstrong777** [isaackogan/TikTokLive#207]
### Describe the bug

When I try to run my code. The error pops up. I thought it was an issue with my code but upon trying the example code, it also didn't work. The weird thing is that my code was running perfectly for hours and now I get this error

### Expected Behaviour

I expected the comments to come through the shell as it does in the example

### Actual Behaviour

Traceback (most recent call last):
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_transports\default.py", line 69, in map_httpcore_exceptions
    yield
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_transports\default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\_async\connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\_async\connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\_async\connection.py", line 101, in handle_async_request
    return await self._connection.handle_async_request(request)
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\_async\http11.py", line 143, in handle_async_request
    raise exc
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\_async\http11.py", line 113, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\_async\http11.py", line 186, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\_async\http11.py", line 224, in _receive_event
    data = await self._network_stream.read(
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\_backends\anyio.py", line 37, in read
    return b""
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python39\lib\idlelib\run.py", line 559, in runcode
    exec(code, self.locals)
  File "D:\TiktokLive\instance-1\scraper.py", line 57, in <module>
    client.run()
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python39\lib\site-packages\TikTokLive\client\client.py", line 171, in run
    return self._asyncio_loop.run_until_complete(self.connect(**kwargs))
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python39\lib\site-packages\TikTokLive\client\client.py", line 153, in connect
    task: Task = await self.start(**kwargs)
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python39\lib\site-packages\TikTokLive\client\client.py", line 127, in start
    webcast_response: WebcastResponse = await self._web.fetch_sign_fetch()
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python39\lib\site-packages\TikTokLive\client\web\routes\fetch_sign.py", line 114, in __call__
    response: Response = await self._web.get_response(
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python39\lib\site-packages\TikTokLive\client\web\web_base.py", line 100, in get_response
    return await (client or self._httpx).get(
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_client.py", line 1801, in get
    return await self.request(
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_client.py", line 1574, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_client.py", line 1661, in send
    response = await self._send_handling_auth(
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_client.py", line 1689, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_client.py", line 1726, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_client.py", line 1763, in _send_single_request
    response = await transport.handle_async_request(request)
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_transports\default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_transports\default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout

### Package Version

V6.0.1

### Operating System

Windows

**Comment by Naatube** [comment]
I got exactly the same issue

**Comment by RyanArmstrong777** [comment]
Out of curiosity, what version of Python are you running your code on?

**Comment by isaackogan** [comment]
Closing in 48h if stale
