### ISSUE TITLE
WebsocketResponseEvent error

### ISSUE THREAD

**Issue by vincespice** [isaackogan/TikTokLive#226]
Hi,

If I want to run the code, I get this error message. What could be the problem?

[TikTokLive] INFO from check_live.py:27 — Requested client is live!
[TikTokLive] INFO from check_live.py:14 — Connected to @carlo_q!
Traceback (most recent call last):
  File "C:\Users\Vince\pycharmprojects\TikTokLive\examples\check_live.py", line 33, in <module>
    asyncio.run(check_loop())
  File "C:\Users\Vince\anaconda3\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Vince\anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\Vince\pycharmprojects\TikTokLive\examples\check_live.py", line 28, in check_loop
    await client.connect()
  File "C:\Users\Vince\pycharmprojects\TikTokLive\TikTokLive\client\client.py", line 185, in connect
    await task
  File "C:\Users\Vince\pycharmprojects\TikTokLive\TikTokLive\client\client.py", line 233, in _client_loop
    async for event in self._ws_loop(initial_response):
  File "C:\Users\Vince\pycharmprojects\TikTokLive\TikTokLive\client\client.py", line 267, in _ws_loop
    for event in self._parse_webcast_response(webcast_message):
  File "C:\Users\Vince\pycharmprojects\TikTokLive\TikTokLive\client\client.py", line 347, in _parse_webcast_response
    response_event: Event = WebsocketResponseEvent().from_pydict(response.to_dict())
AttributeError: 'WebsocketResponseEvent' object has no attribute 'from_pydict'

**Comment by isaackogan** [comment]
oof

**Comment by bperian** [comment]
latest `betterproto==v2.0.0-beta5` works

**Comment by isaackogan** [comment]
Fixed https://github.com/isaackogan/TikTokLive/commit/d96dfcb4c526fd40d80fbfffa13c40d9de724edc
