### ISSUE TITLE
TikTokLive package ceased working on new connections 30 minutes ago

### ISSUE THREAD

**Issue by sjssjssjs** [isaackogan/TikTokLive#23]
Dear team,

The exact same code as previously worked, failed to initiate a connection.

I upgraded TikTokLive to the latest version, and it still no longer connects.

Here is the log.

Any help or update will be useful.
Thanks.
S

ERROR:root:Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\TikTokLive\client\base.py", line 114, in __fetch_room_info
    response = await self._http.get_json_object_from_webcast_api("room/info/", self._client_params)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\TikTokLive\client\http.py", line 144, in get_json_object_from_webcast_api
    response: dict = await self.__aiohttp_get_json(self.TIKTOK_URL_WEBCAST + path, params)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\TikTokLive\client\http.py", line 102, in __aiohttp_get_json
    async with session.get(request_url, headers=self.headers, timeout=self.timeout, proxy=self.proxy_container.get()) as request:
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\aiohttp\client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\aiohttp\client.py", line 559, in _request
    await resp.start(conn)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\aiohttp\client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\aiohttp\streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

Failed to retrieve room info from webcast api
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\TikTokLive\client\base.py", line 215, in _connect
    if self.__room_info.get("status", 4) == 4:
AttributeError: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\Desktop\t.py", line 25, in <module>
    client.run()
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\TikTokLive\client\base.py", line 293, in run
    self.loop.run_until_complete(self._connect())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\TikTokLive\client\client.py", line 38, in _connect
    result: str = await super(TikTokLiveClient, self)._connect()
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\TikTokLive\client\base.py", line 244, in _connect
    raise FailedConnection(message)
TikTokLive.types.errors.FailedConnection: 'NoneType' object has no attribute 'get'

**Comment by bijay077** [comment]
Im having the same issue. looks like the webcast.tiktok.com is not working.

**Comment by sjssjssjs** [comment]
Phew, its not me! Thought so.

Even with the default simple python example, I get the following.

ERROR:root:Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\TikTokLive\client\base.py", line 114, in __fetch_room_info
    response = await self._http.get_json_object_from_webcast_api("room/info/", self._client_params)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\TikTokLive\client\http.py", line 144, in get_json_object_from_webcast_api
    response: dict = await self.__aiohttp_get_json(self.TIKTOK_URL_WEBCAST + path, params)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\TikTokLive\client\http.py", line 102, in __aiohttp_get_json
    async with session.get(request_url, headers=self.headers, timeout=self.timeout, proxy=self.proxy_container.get()) as request:
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\aiohttp\client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\aiohttp\client.py", line 559, in _request
    await resp.start(conn)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\aiohttp\client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\aiohttp\streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [WinError 10054] An existing connection was forcibly closed by the remote host

Failed to retrieve room info from webcast api
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\TikTokLive\client\base.py", line 215, in _connect
    if self.__room_info.get("status", 4) == 4:
AttributeError: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\Desktop\t.py", line 25, in <module>
    client.run()
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\TikTokLive\client\base.py", line 293, in run
    self.loop.run_until_complete(self._connect())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\TikTokLive\client\client.py", line 38, in _connect
    result: str = await super(TikTokLiveClient, self)._connect()
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\TikTokLive\client\base.py", line 244, in _connect
    raise FailedConnection(message)
TikTokLive.types.errors.FailedConnection: 'NoneType' object has no attribute 'get'

**Comment by sjssjssjs** [comment]
Interesting how it kept working all the way up until I restarted my connection. I think it may have to do with initiating the webcast api.

**Comment by bijay077** [comment]
that is what exactly happened to me

**Comment by sjssjssjs** [comment]
Can the developer kindly indicate if he/she might be looking into this?

**Comment by Jimminou** [comment]
Yes I have the same problem since 1 hour.

TikTokLive.types.errors.FailedConnection: 'NoneType' object has no attribute 'get'

**Comment by mikeloski** [comment]
Same for me, I have the same error

**Comment by IronGiu** [comment]
Same error here, but i have bad news for us guys... just try to change username (unique_id) and the "magic" happen... so, for me (my username) webcast do not work and reset connection, with "connection reset by peer" or "server disconnected" error, but if i use another username of another user (just pick one on tik tok, a random one) the webcast work... can it be some sort of ban for specific user that not allowed to use webcast anymore? i changed my ip and all, but nothing work if i use my username...

**Comment by Jimminou** [comment]
> Same error here, but i have bad news for us guys... just try to change username (unique_id) and the "magic" happen... so, for me (my username) webcast do not work and reset connection, with "connection reset by peer" or "server disconnected" error, but if i use another username of another user (just pick one on tik tok, a random one) the webcast work... can it be some sort of ban for specific user that not allowed to use webcast anymore? i changed my ip and all, but nothing work if i use my username...

I dont think because other scripts for NodeJS and other have same settings with the broadcast link, and it's works

**Comment by isaackogan** [comment]
This is being worked on. I sleep, though, so I didn't see this until now

**Comment by noob758745** [comment]
the same error with me

**Comment by isaackogan** [comment]
Fixed in https://github.com/isaackogan/TikTokLive/issues/24
