### ISSUE TITLE
TikTokLive.client.web.routes.fetch_sign.SignAPIError: ('[SIGN_NOT_200]', 'Failed request to Sign API with status code 420.'

### ISSUE THREAD

**Issue by deepin2soul** [isaackogan/TikTokLive#233]
### Describe the bug

Traceback (most recent call last):
  File "C:\Users\Home_I5\Desktop\TikTok\tiktok_py_project\live.py", line 24, in <module>
    client.run()
  File "C:\Users\Home_I5\Desktop\tik_tok311\pythonProject11\venv\Lib\site-packages\TikTokLive\client\client.py", line 167, in run
    return self._asyncio_loop.run_until_complete(self.connect(**kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Home_I5\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Home_I5\Desktop\tik_tok311\pythonProject11\venv\Lib\site-packages\TikTokLive\client\client.py", line 149, in connect
    task: Task = await self.start(**kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Home_I5\Desktop\tik_tok311\pythonProject11\venv\Lib\site-packages\TikTokLive\client\client.py", line 123, in start
    webcast_response: WebcastResponse = await self._web.fetch_sign_fetch()
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Home_I5\Desktop\tik_tok311\pythonProject11\venv\Lib\site-packages\TikTokLive\client\web\routes\fetch_sign.py", line 137, in __call__
    raise SignAPIError(
TikTokLive.client.web.routes.fetch_sign.SignAPIError: ('[SIGN_NOT_200]', 'Failed request to Sign API with status code 420.')
Cancelling an overlapped future failed
future: <_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>
Traceback (most recent call last):
  File "C:\Users\Home_I5\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 71, in _cancel_overlapped
    self._ov.cancel()
OSError: [WinError 6] The handle is invalid

### Expected Behaviour

`...`

### Actual Behaviour
*If applicable, include screenshots!*

`...`

### Package Version

My version of TikTokLive is from 6.0 to 6.0.6

### Operating System

- [x] Windows

### Anything Else

If there's anything else, add it here.

**Comment by shaiyon** [comment]
What steps have you taken to debug this issue? Have you checked if this is a rate limit? Is this a consistent or one off issue?
