### ISSUE TITLE
[TikTokLive] ERROR from t.l.p.s.T.c.client.py:357

### ISSUE THREAD

**Issue by aCS6** [isaackogan/TikTokLive#236]
I am getting 
`ValueError: Too many bytes when decoding varint.` 
randomly. 

Scenerio: I am following a live and capture it's comment. Package can successfully provide the comments, I ran the package for 2.5 hours+ . But randomly 4-5 times I got the error below:

```
[TikTokLive] ERROR from t.l.p.s.T.c.client.py:357 — Traceback (most recent call last):
  File "/home/nahid/test/tiktok-events/one/tik-venv/lib/python3.10/site-packages/TikTokLive/client/client.py", line 355, in _parse_webcast_response
    proto_event: ProtoEvent = event_type().parse(response.payload)
  File "/home/nahid/test/tiktok-events/one/tik-venv/lib/python3.10/site-packages/betterproto/__init__.py", line 1015, in parse
    value = self._postprocess_single(
  File "/home/nahid/test/tiktok-events/one/tik-venv/lib/python3.10/site-packages/betterproto/__init__.py", line 955, in _postprocess_single
    value = cls().parse(value)
  File "/home/nahid/test/tiktok-events/one/tik-venv/lib/python3.10/site-packages/betterproto/__init__.py", line 1015, in parse
    value = self._postprocess_single(
  File "/home/nahid/test/tiktok-events/one/tik-venv/lib/python3.10/site-packages/betterproto/__init__.py", line 955, in _postprocess_single
    value = cls().parse(value)
  File "/home/nahid/test/tiktok-events/one/tik-venv/lib/python3.10/site-packages/betterproto/__init__.py", line 1008, in parse
    decoded, pos = decode_varint(parsed.value, pos)
  File "/home/nahid/test/tiktok-events/one/tik-venv/lib/python3.10/site-packages/betterproto/__init__.py", line 487, in decode_varint
    raise ValueError("Too many bytes when decoding varint.")
ValueError: Too many bytes when decoding varint.

Broken Payload:
b'\n6\n\x14WebcastLinkMicBattle\x10\x88\x96\xc8\xa6\xb3\xb9\xf3\xc1f\x18\x88\x96\xa9\x8a\xe9\x8d\xe0\xc1f \x9e\xe9\xef\x96\x872(\x01\xd0\x01\x01\x10\x88\x96\x94\xb4\xfc\x92\xf3\xc1f\x1a"\x08\x88\x96\x94\xb4\xfc\x92\xf3\xc1f\x10\xb6\x9e\xdd\x96\x872\x18\xad\x02 \x88\x96\x99\xe8\xc1\x8e\xf3\xc1f(\x03@\x01 \x05*\x1a\x08\x86\x88\xa1\xea\xa8\xba\xc8\x9de\x12\x0e\x08\x86\x88\xa1\xea\xa8\xba\xc8\x9de\x10\x01\x18{*\x19\x08\x90\x88\xdf\xee\x80\xfe\xeb\x87f\x12\r\x08\x90\x88\xdf\xee\x80\xfe\xeb\x87f\x18\xd7#J\xfb\x0f\x08\x86\x88\xa1\xea\xa8\xba\xc8\x9de\x12\xee\x0f\n\x96\x05\x08\x82\x88\x85\xf2\xa1\x84\x96\x9cb\x10\x14\x1a\x16\xe5\xa4\xa9\xe8\xa1\x8c\xe8\x80\x85\xef\xbc\x88Skywalker)"\xda\x04\n\x8b\x02https://p16-sign-va.tiktokcdn.com/tos-maliva-avt-0068/4ea37c4f4f99d102cc0bc08e17304003~c5_100x100.webp?lk3s=a5d48078&nonce=5340&refresh_token=30cd34d4e533b18ee82982ee69772abd&x-expires=1720083600&x-signature=MRYZ2MgA3fPGa%2Baq0b3uv0ndY6Q%3D&shp=a5d48078&shcp=d2876c74\n\x8b\x02https://p16-sign-va.tiktokcdn.com/tos-maliva-avt-0068/4ea37c4f4f99d102cc0bc08e17304003~c5_100x100.jpeg?lk3s=a5d48078&nonce=6798&refresh_token=51919381affba516709afadb54ae4fdc&x-expires=1720083600&x-signature=NI8oAIREnLjRGMoDHrh%2B1dUYql4%3D&shp=a5d48078&shcp=d2876c74\x12<100x100/tos-maliva-avt-0068/4ea37c4f4f99d102cc0bc08e173040032\x137077503717972460546\n\x84\x05\x08\x85\x88\xd9\xb6\xae\x94\x8b\xa9`\x10\x05\x1a\x07SubutaY"\xd7\x04\n\x8a\x02https://p16-sign-va.tiktokcdn.com/tos-maliva-avt-0068/01a688d7bec6b16391f2224c77b67240~c5_100x100.webp?lk3s=a5d48078&nonce=18177&refresh_token=b2c9702826bd485871d316380800eb97&x-expires=1720083600&x-signature=m5aNzl7rdnYVZOayOU5XO7KPVMA%3D&shp=a5d48078&shcp=d2876c74\n\x89\x02https://p16-sign-va.tiktokcdn.com/tos-maliva-avt-0068/01a688d7bec6b16391f2224c77b67240~c5_100x100.jpeg?lk3s=a5d48078&nonce=1254&refresh_token=1356a4a8ef2e74d78d1b0d922344ca61&x-expires=1720083600&x-signature=i0ELTXC3TMgGsUIt1Ck9BVKuyAw%3D&shp=a5d48078&shcp=d2876c74\x12<100x100/tos-maliva-avt-0068/01a688d7bec6b16391f2224c77b672402\x136940659053900481541\n\xb4\x05\x08\x81\x88\xd5\xb6\xf6\x85\xd3\xf5c\x10\x04\x1a6\xe0\xb8\x95\xe0\xb8\xb2\xe0\xb8\xa1\xe0\xb8\xad\xe0\xb9\x8a\xe0\xb8\xad\xe0\xb8\x94\xe0\xb8\xa1\xe0\xb8\xb2..\xe0\xb8\x88\xe0\xb8\xb0\xe0\xb8\x9e\xe0\xb8\xb2\xe0\xb8\xa3\xe0\xb8\xa7\xe0\xb8\xa2\xf0\x9f\x92\xb5"\xd8\x04\n\x8a\x02https://p16-sign-va.tiktokcdn.com/tos-maliva-avt-0068/01f624a065bf9631f51ca8f7b83228bc~c5_100x100.webp?lk3s=a5d48078&nonce=53503&refresh_token=ef6aa370f6e0cdb49b95d3cc5b8b076f&x-expires=1720083600&x-signature=oKAs9ntHywaTxn64TXozyma3yzY%3D&shp=a5d48078&shcp=d2876c74\n\x8a\x02https://p16-sign-va.tiktokcdn.com/tos-maliva-avt-0068/01f624a065bf9631f51ca8f7b83228bc~c5_100x100.jpeg?lk3s=a5d48078&nonce=95301&refresh_token=406aa75a828a85007feb8913ecaed8fe&x-expires=1720083600&x-signature=jnRsxn18mVAEz59vVRuPDdO3WiI%3D&shp=a5d48078&shcp=d2876c74\x12<100x100/tos-maliva-avt-0068/01f624a065bf9631f51ca8f7b83228bc2\x137199932195754296321\x10{\x1a\x137294461209653822470J\xee\x11\x08\x90\x88\xdf\xee\x80\xfe\xeb\x87f\x12\xe1\x11\n\x9a\x05\x08\x87\x88\x96\xd2\x96\xff\x99\xfde\x10\x0c\x1a\x15\xe2\x9c\xa8 yo-yo \xf0\x9f\x8f\x8d\xef\xb8\x8f\xf0\x9f\x92\x9b"\xdf\x04\n\x90\x02https://p16-sign-sg.tiktokcdn.com/aweme/100x100/tos-alisg-avt-0068/1f2dab6462018b5d056ae5c90fea0a96.webp?lk3s=a5d48078&nonce=54585&refresh_token=44b699431c7a26849e347a74b639be26&x-expires=1720083600&x-signature=y%2BkbIx5We2qvbL7XCQ7gD3NDT%2B8%3D&shp=a5d48078&shcp=d2876c74\n\x8c\x02https://p16-sign-sg.tiktokcdn.com/aweme/100x100/tos-alisg-avt-0068/1f2dab6462018b5d056ae5c90fea0a96.jpeg?lk3s=a5d48078&nonce=49706&refresh_token=fbba1474da13e0ee0bb80dee1961c593&x-expires=1720083600&x-signature=ffyR8xe9Tl8G0N2DFqhJpWtsfhU%3D&shp=a5d48078&shcp=d2876c74\x12;100x100/tos-alisg-avt-0068/1f2dab6462018b5d056ae5c90fea0a962\x137348300062935843847\n\xc2\x07\x08\x92\x88\xa4\xe8\xde\x8c\xc8\xdbe\x10\n\x1a/c\xc3\xb4 g\xc3\xa1i d\xe1\xbb\x85 th\xc6\xb0\xc6\xa1ng \xf0\x9f\x87\xad\xf0\x9f\x87\xb0\xf0\x9f\x87\xad\xf0\x9f\x87\xb0\xf0\x9f\x87\xad\xf0\x9f\x87\xb0"\xed\x06\n\x8e\x02https://p16-sign-sg.tiktokcdn.com/aweme/100x100/tos-alisg-avt-0068/1c68dfc752bd4a094ae0d693a46c5da8.webp?lk3s=a5d48078&nonce=94280&refresh_token=c8d4f18f92bc27b0f50b897a923cc174&x-expires=1720083600&x-signature=BlWgM3%2B2Fsvh2VxX1qpJZAdIhEQ%3D&shp=a5d48078&shcp=d2876c74\n\x8b\x02https://p9-sign-sg.tiktokcdn.com/aweme/100x100/tos-alisg-avt-0068/1c68dfc752bd4a094ae0d693a46c5da8.webp?lk3s=a5d48078&nonce=57274&refresh_token=897a82252ee31a9da9d8ee625ecffefc&x-expires=1720083600&x-signature=hXC5eqEDkwHFXpYKCw10KxUGXvo%3D&shp=a5d48078&shcp=d2876c74\n\x8e\x02https://p16-sign-sg.tiktokcdn.com/aweme/100x100/tos-alisg-avt-0068/1c68dfc752bd4a094ae0d693a46c5da8.jpeg?lk3s=a5d48078&nonce=60115&refresh_token=56ff6e9d5cca1ea6ae85d1831ef7d306&x-expires=1720083600&x-signature=4E2XqXqxoSZhaF3uCDuhUi%2B0Sc0%3D&shp=a5d48078&shcp=d2876c74\x12;100x100/tos-alisg-avt-0068/1c68dfc752bd4a094ae0d693a46c5da82\x137329362540709348370\n\xe4\x04\x08\x81\x88\xc1\xa2\xfd\x91\xca\xbf_\x10\n\x1a\x06\xe9\x87\xa3\xe5\xae\xa2"\xb8\x04\n\x81\x02https://p16-sign-sg.tiktokcdn.com/aweme/100x100/tos-alisg-avt-0068/7328808157378478082.webp?lk3s=a5d48078&nonce=75486&refresh_token=05f5edb505290e09b038d41148c366be&x-expires=1720083600&x-signature=ezSZZdYfSLD%2F5Ua0uD3ckQJD57M%3D&shp=a5d48078&shcp=d2876c74\n\x81\x02https://p16-sign-sg.tiktokcdn.com/aweme/100x100/tos-alisg-avt-0068/7328808157378478082.jpeg?lk3s=a5d48078&nonce=13695&refresh_token=b8c92570b617aab3d15c6c3d9f0d896d&x-expires=1720083600&x-signature=xpEp1j6jldOwg6nT%2F5ULu8GDGhQ%3D&shp=a5d48078&shcp=d2876c74\x12.100x100/tos-alisg-avt-0068/73288081573784780822\x136881263353852871681\x10\xd7#\x1a\x137354290162078565392R\x8f\x05\x08\x90\x88\xdf\xee\x80\xfe\xeb\x87f\x12\x82\x05\n\xff\x04\x08\x90\x88\xdf\xee\x80\xfe\xeb\x87f\x12\x0e\xe6\x9e\x97\xe6\xb5\xa0Elin\xf0\x9f\x92\x9b\x1a\xd7\x04\n\x8e\x02https://p16-sign-sg.tiktokcdn.com/aweme/100x100/tos-alisg-avt-0068/3a28094c98d12c9a8fa744174b3afcae.webp?lk3s=a5d48078&nonce=13173&refresh_token=fc76bea6c7a83771d9447add40c508df&x-expires=1720083600&x-signature=xqgwzOj5qdPHAPqEePMc7y3n%2BeM%3D&shp=a5d48078&shcp=d2876c74\n\x8e\x02https://p16-sign-sg.tiktokcdn.com/aweme/100x100/tos-alisg-avt-0068/3a28094c98d12c9a8fa744174b3afcae.jpeg?lk3s=a5d48078&nonce=27389&refresh_token=4b5be5a9435cca8716d6462d00643cde&x-expires=1720083600&x-signature=t5rb27II6P4fRzD%2FwR8wEXCr038%3D&shp=a5d48078&shcp=d2876c74\x123tos-alisg-avt-0068/3a28094c98d12c9a8fa744174b3afcae"\tlinxi.888R\x99\x05\x08\x86\x88\xa1\xea\xa8\xba\xc8\x9de\x12\x8c\x05\n\x89\x05\x08\x86\x88\xa1\xea\xa8\xba\xc8\x9de\x12\x16\xf0\x9f\x94\xaeedison\xe2\xad\x90\xef\xb8\x8f\xe2\xad\x90\xef\xb8\x8f\x1a\xd7\x04\n\x8e\x02https://p16-sign-sg.tiktokcdn.com/aweme/100x100/tos-alisg-avt-0068/777ad936b4c93435c0ac181e63fbad36.webp?lk3s=a5d48078&nonce=70327&refresh_token=2711a96d86f6f7db9d41564c17cccace&x-expires=1720083600&x-signature=LwdryBGAe45ZKW%2FDL7T2O4zuwM0%3D&shp=a5d48078&shcp=d2876c74\n\x8e\x02https://p16-sign-sg.tiktokcdn.com/aweme/100x100/tos-alisg-avt-0068/777ad936b4c93435c0ac181e63fbad36.jpeg?lk3s=a5d48078&nonce=32163&refresh_token=2b768f2cf726a4f336a018960cc8b6e8&x-expires=1720083600&x-signature=CHlkv%2Fidx2sQAaTy3rVDRwMfq4c%3D&shp=a5d48078&shcp=d2876c74\x123tos-alisg-avt-0068/777ad936b4c93435c0ac181e63fbad36"\x0bsophiiittxqj\x9f\x03\x08\x90\x88\xdf\xee\x80\xfe\xeb\x87f\x12\x92\x03\x08\x90\x88\xdf\xee\x80\xfe\xeb\x87f\x10\x01\x18\x07(\x012\xff\x02sslocal://webcast_lynxview_popup?url=https%3A%2F%2Flf16-gecko-source.tiktokcdn.com%2Fobj%2Fbyte-gurd-source-sg%2Ftiktok%2Ffe%2Flive%2Ftiktok_live_revenue_match%2Fpages%2Flive_match_streak%2Ftemplate.js&height=832rpx&radius=16rpx&container_bg_color=FFFFFF&bdhm_bid=tiktok_live_revenue_match&bdhm_pid=tiktok_live_revenue_match_pages_live_match_streak&server_room_id=7386889026190068488j\x9d\x03\x08\x86\x88\xa1\xea\xa8\xba\xc8\x9de\x12\x90\x03\x08\x86\x88\xa1\xea\xa8\xba\xc8\x9de\x10\x02(\x012\xff\x02sslocal://webcast_lynxview_popup?url=https%3A%2F%2Flf16-gecko-source.tiktokcdn.com%2Fobj%2Fbyte-gurd-source-sg%2Ftiktok%2Ffe%2Flive%2Ftiktok_live_revenue_match%2Fpages%2Flive_match_streak%2Ftemplate.js&height=832rpx&radius=16rpx&container_bg_color=FFFFFF&bdhm_bid=tiktok_live_revenue_match&bdhm_pid=tiktok_live_revenue_match_pages_live_match_streak&server_room_id=7386968744666352401'
```

But , the package didn't stop and it continued to provide comments. 
How to handle this type of error ? or bypass ?

Thanks

**Comment by isaackogan** [comment]
Option to ignore added in https://github.com/isaackogan/TikTokLive/commit/4f51394aaf054e84271c0fe6752e2b3c060bccd9
