### ISSUE TITLE
6.1.4 error

### ISSUE THREAD

**Issue by ozbao** [isaackogan/TikTokLive#260]
### Describe the bug
![image](https://github.com/user-attachments/assets/c18a42b5-ed37-4027-87d6-6fe9fbacd932)

when i run the example,gifts.py ,report this error

(myenv) PS F:\Work\Tiktok\TikTokLive>  f:; cd 'f:\Work\Tiktok\TikTokLive'; & 'D:\Soft\Anaconda\envs\myenv\python.exe' 'c:\Users\Administrator\.vscode\extensions\ms-python.python-2022.20.2\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher' '17689' '--' 'f:\Work\Tiktok\TikTokLive\examples\gifts.py' 
[TikTokLive] INFO from D:\Soft\Anaconda\envs\myenv\lib\site-packages\websockets\legacy\client.py:605 — ! connect failed; reconnecting in 4.6 seconds
Traceback (most recent call last):
  File "D:\Soft\Anaconda\envs\myenv\lib\site-packages\websockets\legacy\client.py", line 598, in __aiter__
    async with self as protocol:
  File "D:\Soft\Anaconda\envs\myenv\lib\site-packages\websockets\legacy\client.py", line 629, in __aenter__
    return await self
  File "D:\Soft\Anaconda\envs\myenv\lib\site-packages\websockets\legacy\client.py", line 647, in __await_impl_timeout__
    return await self.__await_impl__()
  File "D:\Soft\Anaconda\envs\myenv\lib\site-packages\websockets\legacy\client.py", line 654, in __await_impl__
    await protocol.handshake(
  File "D:\Soft\Anaconda\envs\myenv\lib\site-packages\websockets\legacy\client.py", line 325, in handshake
    raise InvalidStatusCode(status_code, response_headers)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 200
[TikTokLive] INFO from D:\Soft\Anaconda\envs\myenv\lib\site-packages\websockets\legacy\client.py:612 — ! connect failed again; retrying in 3 seconds
Traceback (most recent call last):
  File "D:\Soft\Anaconda\envs\myenv\lib\site-packages\websockets\legacy\client.py", line 598, in __aiter__
    async with self as protocol:
  File "D:\Soft\Anaconda\envs\myenv\lib\site-packages\websockets\legacy\client.py", line 629, in __aenter__
    return await self
  File "D:\Soft\Anaconda\envs\myenv\lib\site-packages\websockets\legacy\client.py", line 647, in __await_impl_timeout__
    return await self.__await_impl__()
  File "D:\Soft\Anaconda\envs\myenv\lib\site-packages\websockets\legacy\client.py", line 654, in __await_impl__
    await protocol.handshake(
  File "D:\Soft\Anaconda\envs\myenv\lib\site-packages\websockets\legacy\client.py", line 325, in handshake
    raise InvalidStatusCode(status_code, response_headers)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 200
### Expected Behaviour

`...`

### Actual Behaviour
*If applicable, include screenshots!*

`...`

### Package Version

My version of TikTokLive is `6.1.4 `.

### Operating System

Windows 11

### Anything Else

If there's anything else, add it here.

**Comment by isaackogan** [comment]
Possibly fixed in https://github.com/isaackogan/TikTokLive/commit/f7632924d75f029c3d8d251c6d5c3daf3ef2e958

Please confirm so I can close, thanks

**Comment by ozbao** [comment]
Yes, it ran successfully

**Comment by isaackogan** [comment]
Woohoo! 

GIF of the Day: https://eelslap.com/
