### ISSUE TITLE
Scraping gifts problem 6.1.5

### ISSUE THREAD

**Issue by Wariie** [isaackogan/TikTokLive#261]
### Describe the bug

After going from v6.1.3 i'm unable to scrap gifts.

### Expected Behaviour

Scrap the gift list 

### Actual Behaviour
*If applicable, include screenshots!*
`Starting TikTokLive client for @radio.chloe
Traceback (most recent call last):
  File "C:\Users\guilh\Desktop\Dev\go_projects\key-event-dispatcher\.venv\lib\site-packages\TikTokLive\client\web\routes\gift_list.py", line 35, in __call__
    return response.json()["data"]
  File "C:\Users\guilh\Desktop\Dev\go_projects\key-event-dispatcher\.venv\lib\site-packages\httpx\_models.py", line 766, in json
    return jsonlib.loads(self.content, **kwargs)
  File "C:\Users\guilh\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\guilh\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\guilh\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\guilh\Desktop\Dev\go_projects\key-event-dispatcher\connector\klyve-connector.py", line 120, in <module>
    start()
  File "C:\Users\guilh\Desktop\Dev\go_projects\key-event-dispatcher\connector\klyve-connector.py", line 117, in start
    client.run(fetch_gift_info=True)
  File "C:\Users\guilh\Desktop\Dev\go_projects\key-event-dispatcher\.venv\lib\site-packages\TikTokLive\client\client.py", line 207, in run
    return self._asyncio_loop.run_until_complete(self.connect(**kwargs))
  File "C:\Users\guilh\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\guilh\Desktop\Dev\go_projects\key-event-dispatcher\.venv\lib\site-packages\TikTokLive\client\client.py", line 183, in connect
    task: Task = await self.start(**kwargs)
  File "C:\Users\guilh\Desktop\Dev\go_projects\key-event-dispatcher\.venv\lib\site-packages\TikTokLive\client\client.py", line 143, in start
    self._gift_info = await self._web.fetch_gift_list()
  File "C:\Users\guilh\Desktop\Dev\go_projects\key-event-dispatcher\.venv\lib\site-packages\TikTokLive\client\web\routes\gift_list.py", line 37, in __call__
    raise FailedFetchGiftListError from ex
TikTokLive.client.web.routes.gift_list.FailedFetchGiftListError
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000000033C4940>
Traceback (most recent call last):
  File "C:\Users\guilh\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Users\guilh\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Users\guilh\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
  File "C:\Users\guilh\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000000033C4940>
Traceback (most recent call last):
  File "C:\Users\guilh\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Users\guilh\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Users\guilh\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
  File "C:\Users\guilh\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed`
`...`

### Package Version

My version of TikTokLive is `6.1.5`.

### Operating System

- [ ] Windows

### Anything Else

If there's anything else, add it here.

**Comment by isaackogan** [comment]
Fixed in https://github.com/isaackogan/TikTokLive/commit/4a4fd2443f2626e329d52e901c236cd584e506f2

**Comment by Wariie** [comment]
Thanks !
