### ISSUE TITLE
FailedConnection: Failed to fetch room id from WebCast

### ISSUE THREAD

**Issue by Tailer12** [isaackogan/TikTokLive#30]
Traceback (most recent call last):
  File "/home/tailer12/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('23.199.71.187', 443)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/tailer12/.local/lib/python3.9/site-packages/TikTokLive/client/base.py", line 110, in __fetch_room_id
    html: str = await self._http.get_livestream_page_html(self.__unique_id)
  File "/home/tailer12/.local/lib/python3.9/site-packages/TikTokLive/client/http.py", line 115, in get_livestream_page_html
    response: bytes = await self.__aiohttp_get_bytes(f"{TikTokHTTPClient.TIKTOK_URL_WEB}@{unique_id}/live")
  File "/home/tailer12/.local/lib/python3.9/site-packages/TikTokLive/client/http.py", line 67, in __aiohttp_get_bytes
    async with session.get(request_url, headers=self.headers, timeout=self.timeout, proxy=self.proxy_container.get()) as request:
  File "/home/tailer12/.local/lib/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/home/tailer12/.local/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/home/tailer12/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/tailer12/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/tailer12/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/home/tailer12/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/home/tailer12/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host www.tiktok.com:443 ssl:default [Connect call failed ('23.199.71.187', 443)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tailer12/.local/lib/python3.9/site-packages/TikTokLive/client/base.py", line 221, in _connect
    await self.__fetch_room_id()
  File "/home/tailer12/.local/lib/python3.9/site-packages/TikTokLive/client/base.py", line 115, in __fetch_room_id
    await self._on_error(ex, FailedFetchRoomInfo("Failed to fetch room id from WebCast, see stacktrace for more info."))
  File "/home/tailer12/.local/lib/python3.9/site-packages/TikTokLive/client/client.py", line 55, in _on_error
    raise _exc
  File "/home/tailer12/.local/lib/python3.9/site-packages/TikTokLive/client/client.py", line 49, in _on_error
    raise append from original
TikTokLive.types.errors.FailedFetchRoomInfo: Failed to fetch room id from WebCast, see stacktrace for more info.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tailer12/my/basic.py", line 52, in <module>
    client.run()
  File "/home/tailer12/.local/lib/python3.9/site-packages/TikTokLive/client/base.py", line 305, in run
    self.loop.run_until_complete(self._connect())
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/tailer12/.local/lib/python3.9/site-packages/TikTokLive/client/client.py", line 87, in _connect
    result: str = await super(TikTokLiveClient, self)._connect()
  File "/home/tailer12/.local/lib/python3.9/site-packages/TikTokLive/client/base.py", line 257, in _connect
    await self._on_error(ex, FailedConnection(message))
  File "/home/tailer12/.local/lib/python3.9/site-packages/TikTokLive/client/client.py", line 55, in _on_error
    raise _exc
  File "/home/tailer12/.local/lib/python3.9/site-packages/TikTokLive/client/client.py", line 49, in _on_error
    raise append from original
TikTokLive.types.errors.FailedConnection: Failed to fetch room id from WebCast, see stacktrace for more info.

**Comment by Tailer12** [comment]
pls help me,i just test the basic.py example,i don't know why,thanks

**Comment by Tailer12** [comment]
search in google,someone say that must change the ip,i had changed 4 ip,and always error,I 'm in china,and use vpn connect to uk

**Comment by Tailer12** [comment]
I'm sorry,the code work well when I change the IP,tiktok ban some ip
