### ISSUE TITLE
TikTokLive.types.errors.FailedConnection

### ISSUE THREAD

**Issue by bazuq** [isaackogan/TikTokLive#39]
Dear developer!

**Code of programme:**

```
from TikTokLive import TikTokLiveClient
from TikTokLive.types.events import ConnectEvent, CommentEvent

sessionid = "bf08457a76b7837a00eec1addc0d62fa"
sid_guard = "bf08457a76b7837a00eec1addc0d62fa%7C1658488742%7C5184000%7CTue%2C+20-Sep-2022+11%3A19%3A02+GMT"

client = TikTokLiveClient("@alon_2021", **{
    "headers": {
        "Cookie": f"sessionid={sessionid}; sid_guard={sid_guard};"
    }
})

@client.on("connect")
async def on_connect(_: ConnectEvent):
    print("Connected to Room ID:", client.room_id)


@client.on("comment")
async def on_comment(event: CommentEvent):
    print(f"{event.user.nickname} -> {event.comment}")


if __name__ == '__main__':
    client.run()
```

**ERROR:**
```
Traceback (most recent call last):
  File "C:\Users\danyl\OneDrive\Рабочий стол\tiktok.py", line 19, in <module>
    client.run()
  File "C:\Users\danyl\AppData\Local\Programs\Python\Python310\lib\site-packages\TikTokLive\client\base.py", line 314, in run
    self.loop.run_until_complete(self._connect())
  File "C:\Users\danyl\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\danyl\AppData\Local\Programs\Python\Python310\lib\site-packages\TikTokLive\client\client.py", line 88, in _connect
    result: str = await super(TikTokLiveClient, self)._connect()
  File "C:\Users\danyl\AppData\Local\Programs\Python\Python310\lib\site-packages\TikTokLive\client\base.py", line 266, in _connect
    await self._on_error(ex, FailedConnection(message))
  File "C:\Users\danyl\AppData\Local\Programs\Python\Python310\lib\site-packages\TikTokLive\client\client.py", line 56, in _on_error
    raise _exc
  File "C:\Users\danyl\AppData\Local\Programs\Python\Python310\lib\site-packages\TikTokLive\client\client.py", line 50, in _on_error
    raise append from original
TikTokLive.types.errors.FailedConnection
```

i have logged into account, and all cookies are valid. it is 100% info
![Screenshot_1](https://user-images.githubusercontent.com/102535317/180429962-84704cef-9230-4b7c-bbf8-1d7ea2a9aa75.png)

**Comment by bazuq** [comment]
What should i do? pls, help me

**Comment by isaackogan** [comment]
They're offline. Change the username to someone online. Lol.

**Comment by Martyshenko** [comment]
Hi, isaackogan, I copied your example, modified it, tested it on an online streamer with login and cookies - got the same error. Literally deleted the "headers" - and connected to the room with the same streamer (just "Connected" no comments or anything)
Judging by the bazuq language near me geographically, this may be related
It is quite puzzling, but i am sure you already have plenty of work, so ill just wait for the new version

**Comment by isaackogan** [comment]
> Hi, isaackogan, I copied your example, modified it, tested it on an online streamer with login and cookies - got the same error. Literally deleted the "headers" - and connected to the room with the same streamer (just "Connected" no comments or anything) Judging by the bazuq language near me geographically, this may be related It is quite puzzling, but i am sure you already have plenty of work, so ill just wait for the new version

Yeah, that's probably best. It's coming out in like, thirty minutes anyways. Let me know if it persists when the new version is released.
