### ISSUE TITLE
Websocket Disconnecting on windows with ver 4.2.6

### ISSUE THREAD

**Issue by generalknow** [isaackogan/TikTokLive#50]
data transfer failed
Traceback (most recent call last):
  File "C:\Users\GeneralKnow\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\protocol.py", line 945, in transfer_data
    message = await self.read_message()
  File "C:\Users\GeneralKnow\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\protocol.py", line 1015, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "C:\Users\GeneralKnow\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\protocol.py", line 1090, in read_data_frame
    frame = await self.read_frame(max_size)
  File "C:\Users\GeneralKnow\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\protocol.py", line 1145, in read_frame
    frame = await Frame.read(
  File "C:\Users\GeneralKnow\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\framing.py", line 100, in read
    data = await reader(length)
  File "C:\Users\GeneralKnow\AppData\Local\Programs\Python\Python310\lib\asyncio\streams.py", line 716, in readexactly
    self._maybe_resume_transport()
  File "C:\Users\GeneralKnow\AppData\Local\Programs\Python\Python310\lib\asyncio\streams.py", line 446, in _maybe_resume_transport
    self._transport.resume_reading()
  File "C:\Users\GeneralKnow\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 343, in resume_reading
    self._ssl_protocol._transport.resume_reading()
AttributeError: 'NoneType' object has no attribute 'resume_reading'
Task exception was never retrieved
future: <Task finished name='Task-9' coro=<WebcastWebsocket.connection_loop() done, defined at C:\Users\GeneralKnow\AppData\Local\Programs\Python\Python310\lib\site-packages\TikTokLive\client\websocket.py:88> exception=ConnectionClosedError(None, Close(code=1011, reason=''), None)>
Traceback (most recent call last):
  File "C:\Users\GeneralKnow\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\protocol.py", line 945, in transfer_data
    message = await self.read_message()
  File "C:\Users\GeneralKnow\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\protocol.py", line 1015, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "C:\Users\GeneralKnow\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\protocol.py", line 1090, in read_data_frame
    frame = await self.read_frame(max_size)
  File "C:\Users\GeneralKnow\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\protocol.py", line 1145, in read_frame
    frame = await Frame.read(
  File "C:\Users\GeneralKnow\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\framing.py", line 100, in read
    data = await reader(length)
  File "C:\Users\GeneralKnow\AppData\Local\Programs\Python\Python310\lib\asyncio\streams.py", line 716, in readexactly
    self._maybe_resume_transport()
  File "C:\Users\GeneralKnow\AppData\Local\Programs\Python\Python310\lib\asyncio\streams.py", line 446, in _maybe_resume_transport
    self._transport.resume_reading()
  File "C:\Users\GeneralKnow\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 343, in resume_reading
    self._ssl_protocol._transport.resume_reading()
AttributeError: 'NoneType' object has no attribute 'resume_reading'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\GeneralKnow\AppData\Local\Programs\Python\Python310\lib\site-packages\TikTokLive\client\websocket.py", line 114, in connection_loop
    self.__client.emit("error", ex)
  File "C:\Users\GeneralKnow\AppData\Local\Programs\Python\Python310\lib\site-packages\pyee\base.py", line 179, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "C:\Users\GeneralKnow\AppData\Local\Programs\Python\Python310\lib\site-packages\pyee\base.py", line 139, in _emit_handle_potential_error
    raise error
  File "C:\Users\GeneralKnow\AppData\Local\Programs\Python\Python310\lib\site-packages\TikTokLive\client\websocket.py", line 104, in connection_loop
    await self.send_ack(decoded["id"])
  File "C:\Users\GeneralKnow\AppData\Local\Programs\Python\Python310\lib\site-packages\TikTokLive\client\websocket.py", line 130, in send_ack
    await self._connection.send(message)
  File "C:\Users\GeneralKnow\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\protocol.py", line 620, in send
    await self.ensure_open()
  File "C:\Users\GeneralKnow\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\protocol.py", line 930, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1011 (unexpected error); no close frame received

**Desktop (please complete the following information):**
 - OS: win10
 - Browser: windows powershell
 - Version 4.2.6

**Comment by isaackogan** [comment]
At this point I think I'll be redoing websockets. For now, disable them

**Comment by Daviko290** [comment]
how can i disable it i have the same problem it works fine for a while and then it fails

**Comment by Daviko290** [comment]
> At this point I think I'll be redoing websockets. For now, disable them

how can i disable it i have the same problem it works fine for a while and then it fails

**Comment by kosmicforger** [comment]
Hey Isaack what's your paypal?

**Comment by isaackogan** [comment]
> Hey Isaack what's your paypal?

PayPal.Me/isaackogan

**Comment by isaackogan** [comment]
> > At this point I think I'll be redoing websockets. For now, disable them
> 
> 
> 
> how can i disable it i have the same problem it works fine for a while and then it fails

I'm not sure it helps anymore. I'm looking into a fix for all of this.

Isaac

**Comment by kosmicforger** [comment]
Do you think this can still be fixed?

**Comment by isaackogan** [comment]
> Do you think this can still be fixed?

I know for a fact it can. Am waiting until I get home.

Isaac

**Comment by yehesmurf** [comment]
> > Do you think this can still be fixed?
> 
> I know for a fact it can. Am waiting until I get home.
> 
> Isaac

how to disable?

**Comment by isaackogan** [comment]
Fixed
