### ISSUE TITLE
Failed connection on startup

### ISSUE THREAD

**Issue by Porksoduh** [isaackogan/TikTokLive#93]
Failed connection error on startup.

CLIENT SETTINGS:
                # Instantiate the client with the user's username
                client: TikTokLiveClient = TikTokLiveClient(unique_id="@laps3d", **(
                        {# Whether to process initial data (cached chats, etc.)
                                "process_initial_data": False,
                        # Custom timeout for Webcast API requests
                                "timeout_ms": 11000,
                        }
                    )
                )

ERROR DISPLAYED AFTER ~14 SECONDS:
      sudo python3 TTLiveV23.py
            Traceback (most recent call last):
              File "/usr/local/lib/python3.7/dist-packages/httpcore/backends/asyncio.py", line 112, in connect_tcp
                local_host=local_address,
              File "/usr/local/lib/python3.7/dist-packages/anyio/_core/_sockets.py", line 218, in connect_tcp
                await event.wait()
              File "/usr/local/lib/python3.7/dist-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
                raise exceptions[0]
              File "/usr/local/lib/python3.7/dist-packages/anyio/_backends/_asyncio.py", line 702, in _run_wrapped_task
                await coro
              File "/usr/local/lib/python3.7/dist-packages/anyio/_core/_sockets.py", line 164, in try_connect
                stream = await asynclib.connect_tcp(remote_host, remote_port, local_address)
              File "/usr/local/lib/python3.7/dist-packages/anyio/_backends/_asyncio.py", line 1692, in connect_tcp
                StreamProtocol, host, port, local_addr=local_addr
              File "/usr/lib/python3.7/asyncio/base_events.py", line 946, in create_connection
                await self.sock_connect(sock, address)
              File "/usr/lib/python3.7/asyncio/selector_events.py", line 464, in sock_connect
                return await fut
            concurrent.futures._base.CancelledError
            
            During handling of the above exception, another exception occurred:
            
            Traceback (most recent call last):
              File "/usr/local/lib/python3.7/dist-packages/httpcore/_exceptions.py", line 8, in map_exceptions
                yield
              File "/usr/local/lib/python3.7/dist-packages/httpcore/backends/asyncio.py", line 112, in connect_tcp
                local_host=local_address,
              File "/usr/local/lib/python3.7/dist-packages/anyio/_core/_tasks.py", line 118, in __exit__
                raise TimeoutError
            TimeoutError
            
            During handling of the above exception, another exception occurred:
            
            Traceback (most recent call last):
              File "/usr/local/lib/python3.7/dist-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
                yield
              File "/usr/local/lib/python3.7/dist-packages/httpx/_transports/default.py", line 353, in handle_async_request
                resp = await self._pool.handle_async_request(req)
              File "/usr/local/lib/python3.7/dist-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
                raise exc
              File "/usr/local/lib/python3.7/dist-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
                response = await connection.handle_async_request(request)
              File "/usr/local/lib/python3.7/dist-packages/httpcore/_async/connection.py", line 86, in handle_async_request
                raise exc
              File "/usr/local/lib/python3.7/dist-packages/httpcore/_async/connection.py", line 63, in handle_async_request
                stream = await self._connect(request)
              File "/usr/local/lib/python3.7/dist-packages/httpcore/_async/connection.py", line 111, in _connect
                stream = await self._network_backend.connect_tcp(**kwargs)
              File "/usr/local/lib/python3.7/dist-packages/httpcore/backends/auto.py", line 30, in connect_tcp
                host, port, timeout=timeout, local_address=local_address
              File "/usr/local/lib/python3.7/dist-packages/httpcore/backends/asyncio.py", line 112, in connect_tcp
                local_host=local_address,
              File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
                self.gen.throw(type, value, traceback)
              File "/usr/local/lib/python3.7/dist-packages/httpcore/_exceptions.py", line 12, in map_exceptions
                raise to_exc(exc)
            httpcore.ConnectTimeout
            
            The above exception was the direct cause of the following exception:
            
            Traceback (most recent call last):
              File "/usr/local/lib/python3.7/dist-packages/TikTokLive/client/base.py", line 402, in _connect
                await self.__fetch_room_data(True)
              File "/usr/local/lib/python3.7/dist-packages/TikTokLive/client/base.py", line 229, in __fetch_room_data
                self._http.get_deserialized_object_from_signing_api("im/fetch/", self._http.params, "WebcastResponse")
              File "/usr/local/lib/python3.7/dist-packages/TikTokLive/client/httpx.py", line 180, in get_deserialized_object_from_signing_api
                response: bytes = await self.__httpx_get_bytes(config.TIKTOK_SIGN_API + path, params, sign_api=True)
              File "/usr/local/lib/python3.7/dist-packages/TikTokLive/client/httpx.py", line 80, in __httpx_get_bytes
                response: httpx.Response = await self.client.get(url, headers=self.headers, timeout=self.timeout)
              File "/usr/local/lib/python3.7/dist-packages/httpx/_client.py", line 1760, in get
                extensions=extensions,
              File "/usr/local/lib/python3.7/dist-packages/httpx/_client.py", line 1527, in request
                return await self.send(request, auth=auth, follow_redirects=follow_redirects)
              File "/usr/local/lib/python3.7/dist-packages/httpx/_client.py", line 1618, in send
                history=[],
              File "/usr/local/lib/python3.7/dist-packages/httpx/_client.py", line 1645, in _send_handling_auth
                history=history,
              File "/usr/local/lib/python3.7/dist-packages/httpx/_client.py", line 1679, in _send_handling_redirects
                response = await self._send_single_request(request)
              File "/usr/local/lib/python3.7/dist-packages/httpx/_client.py", line 1716, in _send_single_request
                response = await transport.handle_async_request(request)
              File "/usr/local/lib/python3.7/dist-packages/httpx/_transports/default.py", line 353, in handle_async_request
                resp = await self._pool.handle_async_request(req)
              File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
                self.gen.throw(type, value, traceback)
              File "/usr/local/lib/python3.7/dist-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
                raise mapped_exc(message) from exc
            httpx.ConnectTimeout
            
            The above exception was the direct cause of the following exception:
            
            Traceback (most recent call last):
              File "TTLiveV23.py", line 557, in <module>
                client.run()
              File "/usr/local/lib/python3.7/dist-packages/TikTokLive/client/base.py", line 483, in run
                self.loop.run_until_complete(self._connect(session_id=session_id))
              File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
                return future.result()
              File "/usr/local/lib/python3.7/dist-packages/TikTokLive/client/client.py", line 86, in _connect
                result: str = await super(TikTokLiveClient, self)._connect(session_id=session_id)
              File "/usr/local/lib/python3.7/dist-packages/TikTokLive/client/base.py", line 434, in _connect
                await self._on_error(ex, FailedConnection(message))
              File "/usr/local/lib/python3.7/dist-packages/TikTokLive/client/client.py", line 54, in _on_error
                raise _exc
              File "/usr/local/lib/python3.7/dist-packages/TikTokLive/client/client.py", line 48, in _on_error
                raise append from original
            TikTokLive.types.errors.FailedConnection

DEVICE:
rPi 4b
Python 3.7

TROUBLESHOOTING DONE:
Reboot rPi
Confirm network connectivity
sudo apt update
sudo apt full-upgrade
Confirmed latest version of TikTokLive

**Comment by sundew01** [comment]
i also have this error i think something has updated breaking the code

**Comment by NathanTubeUrlife** [comment]
I'm having the same issues where it no longer allows me to connect to the user.

**Comment by esalvi** [comment]
Same issue

**Comment by io1337HAPO** [comment]
https://webcast.tiktok.com/webcast/ is down!

"A python library to receive and decode livestream events such as comments and gifts in real-time from TikTok's LIVE service by connecting to TikTok's internal Webcast push service. This library includes a wrapper that connects to the Webcast service using only a user's unique_id and allows you to join your livestream as well as that of other streamers. No credentials are required to use TikTokLive."

What now? :-/

**Comment by geniecode1** [comment]
The same here...**TikTokLive.types.errors.FailedConnection**. But the main exception seems to be related to SSL **ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:1129)**

**Comment by isaackogan** [comment]
Oopsie poopsie

Fixed
